<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_cart_header</name>
   <tag></tag>
   <elementGuidId>fcfc6a5f-c3ea-4c50-b42a-ab329ca0aab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.v-icon.notranslate.fas.fa-shopping-cart.theme--dark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/header/div/button/span/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b621c639-1fee-4e14-9328-e47746913d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>522874d9-e6cf-4f08-8e81-46895b1c02e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate fas fa-shopping-cart theme--dark</value>
      <webElementGuid>28385234-422e-4d99-a951-37686f170065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/header[@class=&quot;v-sheet theme--dark v-toolbar v-app-bar v-app-bar--fixed deep-purple accent-4&quot;]/div[@class=&quot;v-toolbar__content&quot;]/button[@class=&quot;v-btn v-btn--icon v-btn--round theme--dark v-size--default&quot;]/span[@class=&quot;v-btn__content&quot;]/span[@class=&quot;v-badge v-badge--bottom v-badge--left v-badge--overlap theme--dark&quot;]/i[@class=&quot;v-icon notranslate fas fa-shopping-cart theme--dark&quot;]</value>
      <webElementGuid>176645e9-9ddf-42aa-9963-35847001cc2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/header/div/button/span/span/i</value>
      <webElementGuid>a0f0c894-b631-42ea-80d4-f8d4c8f8a96a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AltaShop'])[1]/following::i[1]</value>
      <webElementGuid>289b1278-825c-4632-999c-3c16e593f2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select category ...'])[1]/preceding::i[2]</value>
      <webElementGuid>8f85039b-51d7-44b0-ac3b-8a1684ffc0ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{ firstname: John, lastname:Doe,}'])[1]/preceding::i[3]</value>
      <webElementGuid>a6b162ad-850c-4395-af0b-4435fe6d4cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>0776c3d1-11c9-4b52-b321-89100ee0cf39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
